### PR TITLE
Xendev xenbus fix

### PR DESCRIPTION
**Pull request by ijackson-citrix**
This fixes the header namespace problems in the xebus driver by splitting the driver up.
The privcmd and evtchn drivers have not been tacked yet, and their built remains disabled.

Thanks,
Ian.
[v2: fixed the build when XEN_HEADERS is not already set.  I hadn't appreciated that build-rr.sh runs with set -u]
[v3: fixed the build, avoid using &lt;inttypes.h&gt; in busdev_user.c.  Evidently on my test box it must be picking up a system &lt;Inttypes.h&gt;]

### CODE REVIEW

**Comment by anttikantee** [comment]
re v3: _user.c files *must* pick up system headers (otherwise they can't access the host).
(didn't review everything, that just happened to catch my eye while I was clicking myself up-to-date on github. thanks.)

**Comment by ijackson-citrix** [comment]
Antti Kantee writes ("Re: [rumpkernel/rumprun] Xendev xenbus fix (#83)"):
> re v3: _user.c files must pick up system headers (otherwise they can't access
> the host).
> (didn't review everything, that just happened to catch my eye while I was
> clicking myself up-to-date on github. thanks.)

Thanks for the review.  I'm afraid I don't follow.  The file
busdev_user.c works just fine as it is.  It don't think it needs to
`access the host' in that sense.

Maybe I have some fundamental misunderstanding.  So I will explain
my understanding.  Sorry that this is long.


Background:

Necessarily, building a rump kernel system involves assembling an
image out of C files operating in two separate namespaces.  Each
namespace is both a separate namespace at link-time for external
symbols (done by symbol rewriting) and a separate set of header files.

One of these is the netbsd kernel namespace; the other is for the
application (the "user" namespace).

Certain functions and facilities (eg rump*) are made available in both
namespaces, by providing self-contained sets of headers for their
declarations.  This is one of the ways that calls can be made across
the namespaces.

When targetting a rump kernel at Xen, (a fork of) the xen.git's minios
is used.  minios makes a lot of (IMO unfortunate) assumptions about
the header file and symbol namespaces it lives in.  It wants to be
provided with something roughly like a standard C library.  This is
most easily done by putting minios into the "user" namespace.

Calls by ordinary library functions in the application (or calls
originating in minios) eventually result in "system calls" which are
actually cross-namespace function calls, into the netbsd kernel
namespace.  If the netbsd kernel ultimately needs to implement the
requested operation (eg, write to stdout) with functionality provided
by the platform (in this case Xen), that involves calling back out to
minios.  Normally this is done by a "hypercall" which is actually
again a cross-namespace function call in the other direction.  This
allows different platforms to provide the same facilities and makes
the rump kernels portable to different platforms and operating
environments.


Now on to the xenbus driver in librumpxen_xendev:

The purpose of this module is to provide a /dev/xen/xenbus which can
be used from a rump kernel running on Xen to talk to the system's
actual xenstored.  This is necessary for some Xen-specific rump kernel
applications (such as device models).

The driver needs to do the multiplexing/demultiplexing that is usual
in a kernel xenbus driver, because the application might open the
device multiple times.  It also needs to provide working select()
because the Xen Project userspace libraries which access
/dev/xen/xenbus expect it.

So essentially, this driver needs to implement the complete xenbus
driver interface as might be found in any kernel.  But it needs to be
implemented in terms of the xenstore interface provided by minios.
This is because any one Xen domain has only one xenstore ring
connection.  Other parts of the rump kernel Xen platform support use
minios xenstore support to implement (for example) networking.
minios's xenbus support expects to own the domain's xenstore ring.  So
everything in the rump kernel must use minios to access xenbus.

The minios xenbus support functions do not resemble very much a raw
ring, or indeed the internal xenbus access functions one might find in
a "proper" kernel.  So it is not sensible to try to reuse an ordinary
kernel xenbus driver.  This is why xenbus*.c is bespoke.

It does not make sense to try to provide a xenbus node in /dev when
the platform is not Xen.  So there is no need to make this
functionality available on non-Xen platforms.  It should not be linked
into non-Xen rump kernel images.

Conceptually, therefore, the rump kernel xenbus driver is a single
piece of glue code.

On one side it uses netbsd kernel calls to register a kernel
filesystem entry, provide the appropriate fileops, negotiate with the
netbsd kernel to implement select() for the xenbus fd, and so on.

On the other side it uses minios calls (including callbacks) to send
and receive xenstore commands and replies, and watch events.

Previously this was all in one file.  But that file had to #include
both minios and netbsd headers, violating the separation of
namespaces.  This "header abuse" broke the build.

Now I have split the driver into two pieces.  The separation is rather
arbitrary, and simply designed to reduce the total amount of
unnecessary code and unnecessary abstraction.

There is a single shared header "busdev_user.h" which is included in
both namespaces.  It is entirely self-contained, except that it
requires <xen/io/xs_wire.h>.  That header is part of the Xen public
headers and is itself sensibly namespaced and self-contained.  So as a
whole, #include "busdev_user.h" can be written into both halves of the
xenbus driver.

The common struct contains much of the state of the driver, including
any partially-write(2)'d message from the application, and
declarations of all the functions in either half of the driver which
need calling from the other half.

busdev_user.c is not a piece of the application.  It's in the user
namespace because it needs minios headers.  It does not need anything
else other than some basic C library functions which are also
available in the bmk-* headers.

Am I wrong to #include <bmk-*> ?  xenif_user.c and mini-os/wait.h do
it too.


Thanks for your attention.

Ian.

**Comment by anttikantee** [comment]
On 19/10/16 10:47, Ian Jackson wrote:
> [snip]

yes

> Calls by ordinary library functions in the application (or calls
> originating in minios) eventually result in "system calls" which are
> actually cross-namespace function calls, into the netbsd kernel
> namespace.  If the netbsd kernel ultimately needs to implement the
> requested operation (eg, write to stdout) with functionality provided
> by the platform (in this case Xen), that involves calling back out to
> minios.  Normally this is done by a "hypercall" which is actually
> again a cross-namespace function call in the other direction.  This
> allows different platforms to provide the same facilities and makes
> the rump kernels portable to different platforms and operating
> environments.

Think of the underlying layer, minios(+bmk) in this case, as a firmware. 
  The firmware is separate and doesn't really know what's going on top, 
except for passing initial control and perhaps delivering 
interrupt/exception-type events.  So, normally you wouldn't have calls 
from minios resulting in system calls.  (I'm not sure if you are even 
misunderstanding anything here, given your otherwise rather correct 
understanding, just thought I'd be extra-clear)

> [snip]

more yes

> busdev_user.c is not a piece of the application.  It's in the user
> namespace because it needs minios headers.  It does not need anything
> else other than some basic C library functions which are also
> available in the bmk-* headers.
>
> Am I wrong to #include <bmk-*> ?  xenif_user.c and mini-os/wait.h do
> it too.

You are entirely correct in doing so.

When I said "access the host", I meant access minios routines, perhaps 
that was the source of the confusion.  Also, I didn't mean it as a 
"things are now broken", just as an explanation of why you had to remove 
the use of <inttypes.h>.

**Comment by ijackson-citrix** [comment]
Antti Kantee writes ("Re: [rumpkernel/rumprun] Xendev xenbus fix (#83)"):
> When I said "access the host", I meant access minios routines, perhaps
> that was the source of the confusion. Also, I didn't mean it as a
> "things are now broken", just as an explanation of why you had to remove
> the use of <inttypes.h>.

Oh, I see :-).  Right.  Thanks for your attention.

Ian.

**Pull request merged**
