### PR TITLE
Bump Travis workers OS version to Trusty

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by anttikantee** [comment]
Isn't it possible to get rid of sudo?  It's used only for installing the tools.

**Comment by thedrow** [comment]
It is, but it's a lot more work.

**Comment by thedrow** [comment]
Also, not sure if libxen-dev will work on the containerized workers.

**Comment by anttikantee** [comment]
You seem to know your way around travis, so thought I'd ask ...
Is the ubuntu-toolchain ppa still necessary?

We need only the headers from libxen-dev for building, it's not "used" at all by Travis.

**Comment by thedrow** [comment]
Can you cancel the builds I triggered?
I don't think we need the ubuntu-toolchain ppa anymore.

**Comment by anttikantee** [comment]
Where can I cancel builds from?

**Comment by thedrow** [comment]
See https://blog.travis-ci.com/2013-08-21-abort-mission-cancel-running-builds/

**Comment by anttikantee** [comment]
Thanks for the link, good to know for future reference.
And of course thanks for improving the use of Travis in this repo as well.

**Comment by thedrow** [comment]
No problem :)

**Pull request merged**
