### PR TITLE
Xen event channel device

### PR DESCRIPTION
**Pull request by liuw**
This patch series contains a bunch of fixes to mini-os and provides a userspace event channel device in the last patch.

I've done some preliminary tests with two simple programs that send and receive notification. Poll works, blocking read works, sending notification works. 

For more sophisticated test, I will need to wait until I setup QEMU.

Reviews are welcome.

### CODE REVIEW

**Comment by anttikantee** [comment]
Big picture: it's hard to say anything about locking. It seems like you protect some minios resources with rump kernel locks. I'm not sure that's a good thing in terms of being able to look at the code and understand what is happening. Most critically, a rump kernel does not have interrupts, and therefore it does not have to worry about blocking interrupts before taking a lock which can be used in an interrupt handler.  Since minios has interrupts, it must do that.  I would rather see a cleaner split between the two worlds.

One question: is the user interface equivalent to that offered by regular NetBSD?  (including the path of the device node)

Tell me if you want this pull req merged as such.

**Comment by liuw** [comment]
(Really have no idea how to quote in GitHub comments)

Big picture: ...
The locks in this driver are only for this driver. No lock inside mini-os is held.

One question:...
Yes, the semantics is the same, the path is the same. The device major and minor are not the same, but I don't see a problem at this stage.

Merge:...
I can fix those two minor problems before merging.

**Comment by anttikantee** [comment]
On 07/05/15 14:50, Wei Liu wrote:
> (Really have no idea how to quote in GitHub comments)

I think it works if you reply to the email notification (hopefully ... 
we'll see now ;)

> Big picture: ...
> The locks in this driver are only for this driver. No lock inside mini-os is held.

What is xenevt_ring_lock?

> One question:...
> Yes, the semantics is the same, the path is the same. The device major and minor are not the same, but I don't see a problem at this stage.

Great!  minor/major does not matter.

> Merge:...
> I can fix those two minor problems before merging.

Ok, let me know when you're ready.

**Comment by liuw** [comment]
> On 7 May 2015, at 22:54, Antti Kantee <notifications@github.com> wrote:
> 
> On 07/05/15 14:50, Wei Liu wrote:
> > (Really have no idea how to quote in GitHub comments)
> 
> I think it works if you reply to the email notification (hopefully ... 
> we'll see now ;)
> 

Let me try.

> > Big picture: ...
> > The locks in this driver are only for this driver. No lock inside mini-os is held.
> 
> What is xenevt_ring_lock?
> 

That’s for a global ring inside this driver. It’s not a lock in minios event channel driver.

The evtdev_handler queues events to that ring. Since there can be several interrupts that try to queue events at the same time, a lock is needed.

Then the worker thread will take events off that ring and dispatch it to different users.

> > One question:...
> > Yes, the semantics is the same, the path is the same. The device major and minor are not the same, but I don't see a problem at this stage.
> 
> Great! minor/major does not matter.
> 
> > Merge:...
> > I can fix those two minor problems before merging.
> 
> Ok, let me know when you're ready.

Sure.

**Comment by anttikantee** [comment]
On 07/05/15 15:05, Wei Liu wrote:
>>> Big picture: ...
>>> The locks in this driver are only for this driver. No lock inside mini-os is held.
>>
>> What is xenevt_ring_lock?
>>
>
> That’s for a global ring inside this driver. It’s not a lock in minios event channel driver.
>
> The evtdev_handler queues events to that ring. Since there can be several interrupts that try to queue events at the same time, a lock is needed.
>
> Then the worker thread will take events off that ring and dispatch it to different users.

What I mean by a mini-os lock is that the locking mechanism is a mini-os 
construct.

Btw, is a spinlock really what's needed there?  If you have interrupts 
on in the event handler, won't the second handler just spin forever 
trying to acquire the spinlock?  Also, don't you need irq_save/restore 
on the thread side?

**Pull request closed without merging**
