### PR TITLE
libunwind: Update CPPFLAGS for gcc version 6.2.1

### PR DESCRIPTION
**Pull request by xniine**
1. Mark ${DESTDIR}/usr/include as system headers
2. Ignore shift-negative-value error

### CODE REVIEW

**Comment by anttikantee** [comment]
You can just update your branch, no need to close & open pull reqs per test. I won't merge it before it passes ;-)

**Comment by xniine** [comment]
No worries, I beileve I can still re-open it.  
And you are right, the "shift-negative-value" is better to fix in `llvm/libunwind`.

**Comment by xniine** [comment]
Dont think I can find the correct place to issue a ticket to llvm,  guess I have to write a letter.

**Comment by xniine** [comment]
After checking the original libunwind,  it seems like they are default not enable -Werror. If so the shift-negative-value probablly won`t happend on the llvm/libunwind version.

```cmake
option(LIBUNWIND_ENABLE_WERROR "Fail and stop if a warning is triggered." OFF)
```

```cmake
if (LIBUNWIND_ENABLE_WERROR)
  append_if(LIBUNWIND_COMPILE_FLAGS LIBUNWIND_HAS_WERROR_FLAG -Werror)
  append_if(LIBUNWIND_COMPILE_FLAGS LIBUNWIND_HAS_WX_FLAG -WX)
else()
  append_if(LIBUNWIND_COMPILE_FLAGS LIBUNWIND_HAS_WNO_ERROR_FLAG -Wno-error)
  append_if(LIBUNWIND_COMPILE_FLAGS LIBUNWIND_HAS_NO_WX_FLAG -WX-)
endif()
```

**Comment by anttikantee** [comment]
I meant that you should upstream a fix for the mistake (probably change `-1LL` to `~0ULL`), not a silencing of the warning.

**Comment by xniine** [comment]
The exactly same change was in my shadow, ```-1LL to ~0ULL```, it just cant find ways to report it yet, llvm seems closed it`s registration with the acccount bug reporting and others.

**Comment by xniine** [comment]
and we don`t really need merge it to trunk,since I actully meas to test it with ci

**Pull request closed without merging**
